apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service-https
  namespace: traefik-ingress-controller-ns
  labels:
    app: traefik-ingress-controller
spec:
  type: LoadBalancer
  ports:
    - targetPort: websecure
      port: 443
  selector:
    app: traefik-ingress-controller
